name: iOS Build (Flutter)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: 🔍 Check Flutter and Dart versions
        run: |
          flutter --version
          dart --version

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🔐 Decode firebase_options.dart from base64
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS_B64 }}" | base64 --decode > lib/firebase_options.dart

      - name: 🔐 Decode GoogleService-Info.plist
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST_B64 }}" | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: 🛠️ Install Fastlane
        working-directory: ios
        run: bundle install

      - name: 🚀 Upload to TestFlight with Fastlane
        working-directory: ios
        run: bundle exec fastlane beta
        env:
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APP_STORE_PRIVATE_KEY: ${{ secrets.APP_STORE_PRIVATE_KEY }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          APP_STORE_TEAM_ID: ${{ secrets.APP_STORE_TEAM_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          FASTLANE_DISABLE_COLORS: 1

      - name: ✅ Archive output
        run: |
          mkdir -p build-artifacts
          cp -r build/ios/iphoneos/Runner.app build-artifacts/

      - name: 💾 Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build-artifacts
