name: iOS Build (Flutter)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: 🔍 Check Flutter and Dart versions
        run: |
          flutter --version
          dart --version

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🔍 Show secret preview for debugging
        run: echo "${{ secrets.FIREBASE_OPTIONS_DART }}" | head -c 60

      - name: 🔐 Restore firebase_options.dart
        shell: bash
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS_DART }}" | sed 's/\\n/\n/g' > lib/firebase_options.dart

      - name: 🔧 Build iOS app
        run: flutter build ios --release --no-codesign

      - name: ✅ Archive output
        run: |
          mkdir -p build-artifacts
          cp -r build/ios/iphoneos/Runner.app build-artifacts/

      - name: 💾 Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build-artifacts
